import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

import { cn } from "@/lib/utils";

import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(
          'w-full max-w-[1600px] h-full mx-auto px-6 lg:px-10 xl:px-20',
          font.className
        )}>
          {children}

          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
